const movies = [
    {
    rank: 1,
    title: "The Shawshank Redemption",
    year: 1994,
    runtime: 142,
    rating: 9.3,
    genres: ["Drama"],
    overview: "Two imprisoned men bond over years, finding hope and redemption through friendship.",
    poster: "assets/posters/1.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Shawshank+Redemption+Official+Trailer"
},
{
    rank: 2,
    title: "The Godfather",
    year: 1972,
    runtime: 175,
    rating: 9.2,
    genres: ["Crime","Drama"],
    overview: "The aging patriarch of a powerful crime family transfers control to his reluctant son.",
    poster: "assets/posters/2.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Godfather+Official+Trailer"
},
{
    rank: 3,
    title: "The Dark Knight",
    year: 2008,
    runtime: 152,
    rating: 9.0,
    genres: ["Action","Crime","Drama"],
    overview: "Batman faces the Joker, whose reign of chaos pushes Gotham to its limits.",
    poster: "assets/posters/3.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Dark+Knight+Official+Trailer"
},
{
    rank: 4,
    title: "The Godfather Part II",
    year: 1974,
    runtime: 202,
    rating: 9.0,
    genres: ["Crime","Drama"],
    overview: "The saga of Michael Corleone continues while exploring the early life of Vito Corleone.",
    poster: "assets/posters/4.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Godfather+Part+II+Official+Trailer"
},
{
    rank: 5,
    title: "12 Angry Men",
    year: 1957,
    runtime: 96,
    rating: 9.0,
    genres: ["Crime","Drama"],
    overview: "A lone juror challenges the quick conviction of a teenage defendant.",
    poster: "assets/posters/5.jpg",
    trailer: "https://www.youtube.com/results?search_query=12+Angry+Men+Official+Trailer"
},
{
    rank: 6,
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    runtime: 201,
    rating: 9.0,
    genres: ["Adventure","Drama","Fantasy"],
    overview: "The final battle for Middle-earth begins as Frodo approaches Mount Doom.",
    poster: "assets/posters/6.jpg",
    trailer: "https://www.youtube.com/results?search_query=Return+of+the+King+Official+Trailer"
},
{
    rank: 7,
    title: "Schindler's List",
    year: 1993,
    runtime: 195,
    rating: 9.0,
    genres: ["Biography","Drama","History"],
    overview: "A German businessman saves over a thousand Jewish refugees during World War II.",
    poster: "assets/posters/7.jpg",
    trailer: "https://www.youtube.com/results?search_query=Schindlers+List+Official+Trailer"
},
{
    rank: 8,
    title: "Pulp Fiction",
    year: 1994,
    runtime: 154,
    rating: 8.9,
    genres: ["Crime","Drama"],
    overview: "The lives of several criminals intertwine in Quentin Tarantino's iconic classic.",
    poster: "assets/posters/8.jpg",
    trailer: "https://www.youtube.com/results?search_query=Pulp+Fiction+Official+Trailer"
},
{
    rank: 9,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    year: 2001,
    runtime: 178,
    rating: 8.9,
    genres: ["Adventure","Drama","Fantasy"],
    overview: "A young hobbit begins a dangerous quest to destroy the One Ring.",
    poster: "assets/posters/9.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Fellowship+of+the+Ring+Official+Trailer"
},
{
    rank: 10,
    title: "The Good, the Bad and the Ugly",
    year: 1966,
    runtime: 178,
    rating: 8.8,
    genres: ["Western","Adventure"],
    overview: "Three gunslingers race to find hidden Confederate gold during the Civil War.",
    poster: "assets/posters/10.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Good+the+Bad+and+the+Ugly+Trailer"
},
{
    rank: 11,
    title: "Forrest Gump",
    year: 1994,
    runtime: 142,
    rating: 8.8,
    genres: ["Drama","Romance"],
    overview: "A kind-hearted man unexpectedly influences major moments in American history.",
    poster: "assets/posters/11.jpg",
    trailer: "https://www.youtube.com/results?search_query=Forrest+Gump+Official+Trailer"
},
{
    rank: 12,
    title: "The Lord of the Rings: The Two Towers",
    year: 2002,
    runtime: 179,
    rating: 8.8,
    genres: ["Adventure","Drama","Fantasy"],
    overview: "The Fellowship is broken as the war for Middle-earth intensifies.",
    poster: "assets/posters/12.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Two+Towers+Official+Trailer"
},
{
    rank: 13,
    title: "Fight Club",
    year: 1999,
    runtime: 139,
    rating: 8.8,
    genres: ["Drama"],
    overview: "An office worker forms an underground fight club with a charismatic soap salesman.",
    poster: "assets/posters/13.jpg",
    trailer: "https://www.youtube.com/results?search_query=Fight+Club+Official+Trailer"
},
{
    rank: 14,
    title: "Inception",
    year: 2010,
    runtime: 148,
    rating: 8.8,
    genres: ["Action","Adventure","Sci-Fi"],
    overview: "A skilled thief enters dreams to steal secrets and perform the impossible.",
    poster: "assets/posters/14.jpg",
    trailer: "https://www.youtube.com/results?search_query=Inception+Official+Trailer"
},
{
    rank: 15,
    title: "Star Wars: Episode V – The Empire Strikes Back",
    year: 1980,
    runtime: 124,
    rating: 8.7,
    genres: ["Action","Adventure","Fantasy"],
    overview: "Luke Skywalker trains with Yoda while Darth Vader hunts the Rebel Alliance.",
    poster: "assets/posters/15.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Empire+Strikes+Back+Official+Trailer"
},
{
    rank: 16,
    title: "The Matrix",
    year: 1999,
    runtime: 136,
    rating: 8.7,
    genres: ["Action","Sci-Fi"],
    overview: "A hacker discovers the shocking truth about reality and humanity's future.",
    poster: "assets/posters/16.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Matrix+Official+Trailer"
},
{
    rank: 17,
    title: "Goodfellas",
    year: 1990,
    runtime: 145,
    rating: 8.7,
    genres: ["Biography","Crime","Drama"],
    overview: "The rise and fall of mob associate Henry Hill inside the American Mafia.",
    poster: "assets/posters/17.jpg",
    trailer: "https://www.youtube.com/results?search_query=Goodfellas+Official+Trailer"
},
{
    rank: 18,
    title: "One Flew Over the Cuckoo's Nest",
    year: 1975,
    runtime: 133,
    rating: 8.7,
    genres: ["Drama"],
    overview: "A rebellious criminal challenges the oppressive routine of a mental institution.",
    poster: "assets/posters/18.jpg",
    trailer: "https://www.youtube.com/results?search_query=One+Flew+Over+the+Cuckoos+Nest+Trailer"
},
{
    rank: 19,
    title: "Se7en",
    year: 1995,
    runtime: 127,
    rating: 8.6,
    genres: ["Crime","Drama","Mystery"],
    overview: "Two detectives hunt a serial killer inspired by the seven deadly sins.",
    poster: "assets/posters/19.jpg",
    trailer: "https://www.youtube.com/results?search_query=Se7en+Official+Trailer"
},
{
    rank: 20,
    title: "It's a Wonderful Life",
    year: 1946,
    runtime: 130,
    rating: 8.6,
    genres: ["Drama","Family","Fantasy"],
    overview: "An angel shows a struggling man what life would have been like without him.",
    poster: "assets/posters/20.jpg",
    trailer: "https://www.youtube.com/results?search_query=Its+a+Wonderful+Life+Trailer"
},
{
    rank: 21,
    title: "Seven Samurai",
    year: 1954,
    runtime: 207,
    rating: 8.6,
    genres: ["Action","Drama"],
    overview: "Seven masterless samurai defend a poor village from ruthless bandits.",
    poster: "assets/posters/21.jpg",
    trailer: "https://www.youtube.com/results?search_query=Seven+Samurai+Trailer"
},
{
    rank: 22,
    title: "The Silence of the Lambs",
    year: 1991,
    runtime: 118,
    rating: 8.6,
    genres: ["Crime","Drama","Thriller"],
    overview: "A young FBI trainee seeks the help of Hannibal Lecter to catch a serial killer.",
    poster: "assets/posters/22.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Silence+of+the+Lambs+Trailer"
},
{
    rank: 23,
    title: "Saving Private Ryan",
    year: 1998,
    runtime: 169,
    rating: 8.6,
    genres: ["Drama","War"],
    overview: "A group of soldiers search for a paratrooper during World War II.",
    poster: "assets/posters/23.jpg",
    trailer: "https://www.youtube.com/results?search_query=Saving+Private+Ryan+Official+Trailer"
},
{
    rank: 24,
    title: "City of God",
    year: 2002,
    runtime: 130,
    rating: 8.6,
    genres: ["Crime","Drama"],
    overview: "Two boys grow up in a violent Rio de Janeiro neighborhood following different paths.",
    poster: "assets/posters/24.jpg",
    trailer: "https://www.youtube.com/results?search_query=City+of+God+Official+Trailer"
},
{
    rank: 25,
    title: "Interstellar",
    year: 2014,
    runtime: 169,
    rating: 8.7,
    genres: ["Adventure","Drama","Sci-Fi"],
    overview: "Explorers travel through a wormhole in search of humanity's future beyond Earth.",
    poster: "assets/posters/25.jpg",
    trailer: "https://www.youtube.com/results?search_query=Interstellar+Official+Trailer"
},
{
    rank: 26,
    title: "Life Is Beautiful",
    year: 1997,
    runtime: 116,
    rating: 8.6,
    genres: ["Comedy", "Drama", "Romance"],
    overview: "A devoted father uses humor and imagination to protect his son from the horrors of a concentration camp.",
    poster: "assets/posters/26.jpg",
    trailer: "https://www.youtube.com/results?search_query=Life+Is+Beautiful+Official+Trailer"
},
{
    rank: 27,
    title: "The Green Mile",
    year: 1999,
    runtime: 189,
    rating: 8.6,
    genres: ["Crime", "Drama", "Fantasy"],
    overview: "A death row prison guard discovers that one inmate possesses extraordinary healing powers.",
    poster: "assets/posters/27.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Green+Mile+Official+Trailer"
},
{
    rank: 28,
    title: "Terminator 2: Judgment Day",
    year: 1991,
    runtime: 137,
    rating: 8.6,
    genres: ["Action", "Sci-Fi"],
    overview: "A reprogrammed Terminator is sent back in time to protect humanity's future leader.",
    poster: "assets/posters/28.jpg",
    trailer: "https://www.youtube.com/results?search_query=Terminator+2+Judgment+Day+Official+Trailer"
},
{
    rank: 29,
    title: "Star Wars: Episode IV – A New Hope",
    year: 1977,
    runtime: 121,
    rating: 8.6,
    genres: ["Action", "Adventure", "Fantasy"],
    overview: "Luke Skywalker joins forces with rebels to battle the evil Galactic Empire.",
    poster: "assets/posters/29.jpg",
    trailer: "https://www.youtube.com/results?search_query=Star+Wars+A+New+Hope+Official+Trailer"
},
{
    rank: 30,
    title: "Back to the Future",
    year: 1985,
    runtime: 116,
    rating: 8.5,
    genres: ["Adventure", "Comedy", "Sci-Fi"],
    overview: "A teenager accidentally travels to the past and must ensure his parents fall in love.",
    poster: "assets/posters/30.jpg",
    trailer: "https://www.youtube.com/results?search_query=Back+to+the+Future+Official+Trailer"
},
{
    rank: 31,
    title: "Spirited Away",
    year: 2001,
    runtime: 125,
    rating: 8.6,
    genres: ["Animation", "Adventure", "Family"],
    overview: "A young girl enters a magical spirit world where she must save her parents.",
    poster: "assets/posters/31.jpg",
    trailer: "https://www.youtube.com/results?search_query=Spirited+Away+Official+Trailer"
},
{
    rank: 32,
    title: "Psycho",
    year: 1960,
    runtime: 109,
    rating: 8.5,
    genres: ["Horror", "Mystery", "Thriller"],
    overview: "A secretary on the run checks into a lonely motel run by the mysterious Norman Bates.",
    poster: "assets/posters/32.jpg",
    trailer: "https://www.youtube.com/results?search_query=Psycho+1960+Official+Trailer"
},
{
    rank: 33,
    title: "The Pianist",
    year: 2002,
    runtime: 150,
    rating: 8.5,
    genres: ["Biography", "Drama", "Music"],
    overview: "A gifted pianist struggles to survive the destruction of Warsaw during World War II.",
    poster: "assets/posters/33.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Pianist+Official+Trailer"
},
{
    rank: 34,
    title: "Parasite",
    year: 2019,
    runtime: 132,
    rating: 8.5,
    genres: ["Drama", "Thriller"],
    overview: "A poor family cleverly infiltrates the lives of a wealthy household with unexpected consequences.",
    poster: "assets/posters/34.jpg",
    trailer: "https://www.youtube.com/results?search_query=Parasite+Official+Trailer"
},
{
    rank: 35,
    title: "The Lion King",
    year: 1994,
    runtime: 88,
    rating: 8.5,
    genres: ["Animation", "Adventure", "Drama"],
    overview: "A young lion prince flees his kingdom only to return and reclaim his rightful place.",
    poster: "assets/posters/35.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Lion+King+1994+Official+Trailer"
},
{
    rank: 36,
    title: "Gladiator",
    year: 2000,
    runtime: 155,
    rating: 8.5,
    genres: ["Action", "Adventure", "Drama"],
    overview: "A betrayed Roman general fights as a gladiator to avenge his family and emperor.",
    poster: "assets/posters/36.jpg",
    trailer: "https://www.youtube.com/results?search_query=Gladiator+Official+Trailer"
},
{
    rank: 37,
    title: "American History X",
    year: 1998,
    runtime: 119,
    rating: 8.5,
    genres: ["Crime", "Drama"],
    overview: "A former neo-Nazi tries to stop his younger brother from following the same violent path.",
    poster: "assets/posters/37.jpg",
    trailer: "https://www.youtube.com/results?search_query=American+History+X+Official+Trailer"
},
{
    rank: 38,
    title: "The Departed",
    year: 2006,
    runtime: 151,
    rating: 8.5,
    genres: ["Crime", "Drama", "Thriller"],
    overview: "An undercover cop and a police mole race to uncover each other's identity.",
    poster: "assets/posters/38.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Departed+Official+Trailer"
},
{
    rank: 39,
    title: "The Prestige",
    year: 2006,
    runtime: 130,
    rating: 8.5,
    genres: ["Drama", "Mystery", "Sci-Fi"],
    overview: "Two rival magicians become obsessed with creating the ultimate illusion.",
    poster: "assets/posters/39.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Prestige+Official+Trailer"
},
{
    rank: 40,
    title: "Whiplash",
    year: 2014,
    runtime: 106,
    rating: 8.5,
    genres: ["Drama", "Music"],
    overview: "A talented drummer endures the relentless pressure of a demanding music instructor.",
    poster: "assets/posters/40.jpg",
    trailer: "https://www.youtube.com/results?search_query=Whiplash+Official+Trailer"
},
{
    rank: 41,
    title: "The Usual Suspects",
    year: 1995,
    runtime: 106,
    rating: 8.5,
    genres: ["Crime", "Drama", "Mystery"],
    overview: "A mysterious criminal mastermind is revealed through the testimony of a survivor.",
    poster: "assets/posters/41.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Usual+Suspects+Official+Trailer"
},
{
    rank: 42,
    title: "Harakiri",
    year: 1962,
    runtime: 133,
    rating: 8.6,
    genres: ["Action", "Drama", "Mystery"],
    overview: "A ronin's request to commit ritual suicide reveals a tragic tale of honor and revenge.",
    poster: "assets/posters/42.jpg",
    trailer: "https://www.youtube.com/results?search_query=Harakiri+1962+Trailer"
},
{
    rank: 43,
    title: "Grave of the Fireflies",
    year: 1988,
    runtime: 89,
    rating: 8.5,
    genres: ["Animation", "Drama", "War"],
    overview: "Two siblings struggle to survive in Japan during the final months of World War II.",
    poster: "assets/posters/43.jpg",
    trailer: "https://www.youtube.com/results?search_query=Grave+of+the+Fireflies+Trailer"
},
{
    rank: 44,
    title: "Casablanca",
    year: 1942,
    runtime: 102,
    rating: 8.5,
    genres: ["Drama", "Romance", "War"],
    overview: "An American expatriate must choose between love and helping resistance fighters.",
    poster: "assets/posters/44.jpg",
    trailer: "https://www.youtube.com/results?search_query=Casablanca+Official+Trailer"
},
{
    rank: 45,
    title: "Léon: The Professional",
    year: 1994,
    runtime: 110,
    rating: 8.5,
    genres: ["Action", "Crime", "Drama"],
    overview: "A lonely hitman reluctantly takes in a young girl after her family is murdered.",
    poster: "assets/posters/45.jpg",
    trailer: "https://www.youtube.com/results?search_query=Leon+The+Professional+Official+Trailer"
},
{
    rank: 46,
    title: "Rear Window",
    year: 1954,
    runtime: 112,
    rating: 8.5,
    genres: ["Mystery", "Thriller"],
    overview: "A wheelchair-bound photographer suspects his neighbor has committed murder.",
    poster: "assets/posters/46.jpg",
    trailer: "https://www.youtube.com/results?search_query=Rear+Window+Official+Trailer"
},
{
    rank: 47,
    title: "Cinema Paradiso",
    year: 1988,
    runtime: 155,
    rating: 8.5,
    genres: ["Drama", "Romance"],
    overview: "A filmmaker remembers his childhood friendship with a projectionist in a small Sicilian town.",
    poster: "assets/posters/47.jpg",
    trailer: "https://www.youtube.com/results?search_query=Cinema+Paradiso+Official+Trailer"
},
{
    rank: 48,
    title: "Modern Times",
    year: 1936,
    runtime: 87,
    rating: 8.5,
    genres: ["Comedy", "Drama", "Romance"],
    overview: "Charlie Chaplin's Little Tramp struggles to survive in the industrial age.",
    poster: "assets/posters/48.jpg",
    trailer: "https://www.youtube.com/results?search_query=Modern+Times+Official+Trailer"
},
{
    rank: 49,
    title: "Once Upon a Time in the West",
    year: 1968,
    runtime: 165,
    rating: 8.5,
    genres: ["Western"],
    overview: "A mysterious harmonica player joins forces to protect a widow from a ruthless assassin.",
    poster: "assets/posters/49.jpg",
    trailer: "https://www.youtube.com/results?search_query=Once+Upon+a+Time+in+the+West+Trailer"
},
{
    rank: 50,
    title: "Alien",
    year: 1979,
    runtime: 117,
    rating: 8.5,
    genres: ["Horror", "Sci-Fi"],
    overview: "The crew of a commercial spaceship is hunted by a deadly extraterrestrial creature.",
    poster: "assets/posters/50.jpg",
    trailer: "https://www.youtube.com/results?search_query=Alien+1979+Official+Trailer"
},
{
    rank: 51,
    title: "City Lights",
    year: 1931,
    runtime: 87,
    rating: 8.5,
    genres: ["Comedy", "Drama", "Romance"],
    overview: "The Little Tramp falls in love with a blind flower girl while trying to help her.",
    poster: "assets/posters/51.jpg",
    trailer: "https://www.youtube.com/results?search_query=City+Lights+Official+Trailer"
},
{
    rank: 52,
    title: "Apocalypse Now",
    year: 1979,
    runtime: 147,
    rating: 8.4,
    genres: ["Drama", "Mystery", "War"],
    overview: "A U.S. Army officer travels into the jungle to eliminate a rogue colonel.",
    poster: "assets/posters/52.jpg",
    trailer: "https://www.youtube.com/results?search_query=Apocalypse+Now+Official+Trailer"
},
{
    rank: 53,
    title: "Django Unchained",
    year: 2012,
    runtime: 165,
    rating: 8.5,
    genres: ["Drama", "Western"],
    overview: "A freed slave teams up with a bounty hunter to rescue his wife.",
    poster: "assets/posters/53.jpg",
    trailer: "https://www.youtube.com/results?search_query=Django+Unchained+Official+Trailer"
},
{
    rank: 54,
    title: "Memento",
    year: 2000,
    runtime: 113,
    rating: 8.4,
    genres: ["Mystery", "Thriller"],
    overview: "A man with short-term memory loss searches for his wife's killer.",
    poster: "assets/posters/54.jpg",
    trailer: "https://www.youtube.com/results?search_query=Memento+Official+Trailer"
},
{
    rank: 55,
    title: "Raiders of the Lost Ark",
    year: 1981,
    runtime: 115,
    rating: 8.4,
    genres: ["Action", "Adventure"],
    overview: "Indiana Jones races against the Nazis to find the legendary Ark of the Covenant.",
    poster: "assets/posters/55.jpg",
    trailer: "https://www.youtube.com/results?search_query=Raiders+of+the+Lost+Ark+Official+Trailer"
},
{
    rank: 56,
    title: "WALL·E",
    year: 2008,
    runtime: 98,
    rating: 8.4,
    genres: ["Animation", "Adventure", "Family"],
    overview: "A lonely waste-collecting robot embarks on an unexpected space adventure.",
    poster: "assets/posters/56.jpg",
    trailer: "https://www.youtube.com/results?search_query=WALL-E+Official+Trailer"
},
{
    rank: 57,
    title: "The Lives of Others",
    year: 2006,
    runtime: 137,
    rating: 8.4,
    genres: ["Drama", "Mystery", "Thriller"],
    overview: "An East German secret police officer becomes emotionally involved with his surveillance targets.",
    poster: "assets/posters/57.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Lives+of+Others+Official+Trailer"
},
{
    rank: 58,
    title: "Sunset Boulevard",
    year: 1950,
    runtime: 110,
    rating: 8.4,
    genres: ["Drama", "Film-Noir"],
    overview: "A struggling screenwriter becomes trapped in the world of a faded silent film star.",
    poster: "assets/posters/58.jpg",
    trailer: "https://www.youtube.com/results?search_query=Sunset+Boulevard+Official+Trailer"
},
{
    rank: 59,
    title: "Paths of Glory",
    year: 1957,
    runtime: 88,
    rating: 8.4,
    genres: ["Drama", "War"],
    overview: "A French army colonel defends soldiers accused of cowardice during World War I.",
    poster: "assets/posters/59.jpg",
    trailer: "https://www.youtube.com/results?search_query=Paths+of+Glory+Official+Trailer"
},
{
    rank: 60,
    title: "Avengers: Infinity War",
    year: 2018,
    runtime: 149,
    rating: 8.4,
    genres: ["Action", "Adventure", "Sci-Fi"],
    overview: "The Avengers unite to stop Thanos from collecting all six Infinity Stones.",
    poster: "assets/posters/60.jpg",
    trailer: "https://www.youtube.com/results?search_query=Avengers+Infinity+War+Official+Trailer"
},
{
    rank: 61,
    title: "Witness for the Prosecution",
    year: 1957,
    runtime: 116,
    rating: 8.4,
    genres: ["Crime", "Drama", "Mystery"],
    overview: "A veteran lawyer defends a man accused of murdering a wealthy widow.",
    poster: "assets/posters/61.jpg",
    trailer: "https://www.youtube.com/results?search_query=Witness+for+the+Prosecution+Trailer"
},
{
    rank: 62,
    title: "The Shining",
    year: 1980,
    runtime: 146,
    rating: 8.4,
    genres: ["Drama", "Horror"],
    overview: "A writer slowly loses his sanity while isolated in a haunted hotel.",
    poster: "assets/posters/62.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Shining+Official+Trailer"
},
{
    rank: 63,
    title: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    runtime: 117,
    rating: 8.4,
    genres: ["Animation", "Action", "Adventure"],
    overview: "Miles Morales joins Spider-People from different universes to save reality.",
    poster: "assets/posters/63.jpg",
    trailer: "https://www.youtube.com/results?search_query=Spider-Man+Into+the+Spider-Verse+Official+Trailer"
},
{
    rank: 64,
    title: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    year: 1964,
    runtime: 95,
    rating: 8.4,
    genres: ["Comedy", "War"],
    overview: "Political leaders scramble to prevent a nuclear catastrophe after a rogue general acts.",
    poster: "assets/posters/64.jpg",
    trailer: "https://www.youtube.com/results?search_query=Dr+Strangelove+Official+Trailer"
},
{
    rank: 65,
    title: "The Great Dictator",
    year: 1940,
    runtime: 125,
    rating: 8.4,
    genres: ["Comedy", "Drama", "War"],
    overview: "Charlie Chaplin satirizes fascism in one of cinema's most iconic political comedies.",
    poster: "assets/posters/65.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Great+Dictator+Official+Trailer"
},
{
    rank: 66,
    title: "Aliens",
    year: 1986,
    runtime: 137,
    rating: 8.4,
    genres: ["Action", "Adventure", "Sci-Fi"],
    overview: "Ripley returns to face terrifying alien creatures with a squad of space marines.",
    poster: "assets/posters/66.jpg",
    trailer: "https://www.youtube.com/results?search_query=Aliens+1986+Official+Trailer"
},
{
    rank: 67,
    title: "Inglourious Basterds",
    year: 2009,
    runtime: 153,
    rating: 8.4,
    genres: ["Adventure", "Drama", "War"],
    overview: "A group of Jewish-American soldiers plot revenge against the Nazi regime.",
    poster: "assets/posters/67.jpg",
    trailer: "https://www.youtube.com/results?search_query=Inglourious+Basterds+Official+Trailer"
},
{
    rank: 68,
    title: "The Dark Knight Rises",
    year: 2012,
    runtime: 164,
    rating: 8.4,
    genres: ["Action", "Drama"],
    overview: "Batman returns from exile to face the merciless revolutionary Bane.",
    poster: "assets/posters/68.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Dark+Knight+Rises+Official+Trailer"
},
{
    rank: 69,
    title: "American Beauty",
    year: 1999,
    runtime: 122,
    rating: 8.3,
    genres: ["Drama"],
    overview: "A suburban father experiences a midlife crisis that changes his family's lives forever.",
    poster: "assets/posters/69.jpg",
    trailer: "https://www.youtube.com/results?search_query=American+Beauty+Official+Trailer"
},
{
    rank: 70,
    title: "The Lives of Others",
    year: 2006,
    runtime: 137,
    rating: 8.4,
    genres: ["Drama", "Mystery", "Thriller"],
    overview: "An East German surveillance officer begins questioning his loyalties while spying on artists.",
    poster: "assets/posters/70.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Lives+of+Others+Official+Trailer"
},
{
    rank: 71,
    title: "Coco",
    year: 2017,
    runtime: 105,
    rating: 8.4,
    genres: ["Animation", "Adventure", "Family"],
    overview: "A young musician journeys into the Land of the Dead to uncover his family's history.",
    poster: "assets/posters/71.jpg",
    trailer: "https://www.youtube.com/results?search_query=Coco+Official+Trailer"
},
{
    rank: 72,
    title: "Oldboy",
    year: 2003,
    runtime: 120,
    rating: 8.4,
    genres: ["Action", "Drama", "Mystery"],
    overview: "After years of mysterious imprisonment, a man seeks vengeance and the truth.",
    poster: "assets/posters/72.jpg",
    trailer: "https://www.youtube.com/results?search_query=Oldboy+2003+Official+Trailer"
},
{
    rank: 73,
    title: "Amadeus",
    year: 1984,
    runtime: 160,
    rating: 8.4,
    genres: ["Biography", "Drama", "Music"],
    overview: "Antonio Salieri reflects on his rivalry with the brilliant Wolfgang Amadeus Mozart.",
    poster: "assets/posters/73.jpg",
    trailer: "https://www.youtube.com/results?search_query=Amadeus+Official+Trailer"
},
{
    rank: 74,
    title: "Toy Story",
    year: 1995,
    runtime: 81,
    rating: 8.3,
    genres: ["Animation", "Adventure", "Comedy"],
    overview: "A cowboy doll's world changes when a flashy new space ranger arrives.",
    poster: "assets/posters/74.jpg",
    trailer: "https://www.youtube.com/results?search_query=Toy+Story+Official+Trailer"
},
{
    rank: 75,
    title: "Braveheart",
    year: 1995,
    runtime: 178,
    rating: 8.3,
    genres: ["Biography", "Drama", "History"],
    overview: "Scottish warrior William Wallace leads a rebellion against English rule.",
    poster: "assets/posters/75.jpg",
    trailer: "https://www.youtube.com/results?search_query=Braveheart+Official+Trailer"
},
{
    rank: 76,
    title: "Das Boot",
    year: 1981,
    runtime: 149,
    rating: 8.4,
    genres: ["Drama", "War"],
    overview: "The crew of a German U-boat faces relentless danger during World War II.",
    poster: "assets/posters/76.jpg",
    trailer: "https://www.youtube.com/results?search_query=Das+Boot+Official+Trailer"
},
{
    rank: 77,
    title: "Joker",
    year: 2019,
    runtime: 122,
    rating: 8.4,
    genres: ["Crime", "Drama", "Thriller"],
    overview: "A failed comedian descends into madness and becomes Gotham City's infamous Joker.",
    poster: "assets/posters/77.jpg",
    trailer: "https://www.youtube.com/results?search_query=Joker+2019+Official+Trailer"
},
{
    rank: 78,
    title: "Avengers: Endgame",
    year: 2019,
    runtime: 181,
    rating: 8.4,
    genres: ["Action", "Adventure", "Sci-Fi"],
    overview: "The Avengers assemble one final time to undo the devastation caused by Thanos.",
    poster: "assets/posters/78.jpg",
    trailer: "https://www.youtube.com/results?search_query=Avengers+Endgame+Official+Trailer"
},
{
    rank: 79,
    title: "Princess Mononoke",
    year: 1997,
    runtime: 134,
    rating: 8.4,
    genres: ["Animation", "Adventure", "Fantasy"],
    overview: "A young warrior becomes caught in a struggle between humans and forest gods.",
    poster: "assets/posters/79.jpg",
    trailer: "https://www.youtube.com/results?search_query=Princess+Mononoke+Official+Trailer"
},
{
    rank: 80,
    title: "Your Name.",
    year: 2016,
    runtime: 106,
    rating: 8.4,
    genres: ["Animation", "Drama", "Fantasy"],
    overview: "Two teenagers mysteriously swap bodies and form an unforgettable connection.",
    poster: "assets/posters/80.jpg",
    trailer: "https://www.youtube.com/results?search_query=Your+Name+Official+Trailer"
},
{
    rank: 81,
    title: "Once Upon a Time in America",
    year: 1984,
    runtime: 229,
    rating: 8.3,
    genres: ["Crime", "Drama"],
    overview: "An aging gangster reflects on his youth and lifelong friendships in New York.",
    poster: "assets/posters/81.jpg",
    trailer: "https://www.youtube.com/results?search_query=Once+Upon+a+Time+in+America+Official+Trailer"
},
{
    rank: 82,
    title: "Good Will Hunting",
    year: 1997,
    runtime: 126,
    rating: 8.3,
    genres: ["Drama", "Romance"],
    overview: "A mathematical genius finds guidance through an unconventional therapist.",
    poster: "assets/posters/82.jpg",
    trailer: "https://www.youtube.com/results?search_query=Good+Will+Hunting+Official+Trailer"
},
{
    rank: 83,
    title: "3 Idiots",
    year: 2009,
    runtime: 170,
    rating: 8.4,
    genres: ["Comedy", "Drama"],
    overview: "Three engineering students challenge the pressures of India's education system.",
    poster: "assets/posters/83.jpg",
    trailer: "https://www.youtube.com/results?search_query=3+Idiots+Official+Trailer"
},
{
    rank: 84,
    title: "Requiem for a Dream",
    year: 2000,
    runtime: 102,
    rating: 8.3,
    genres: ["Drama"],
    overview: "The lives of four people unravel due to addiction and shattered dreams.",
    poster: "assets/posters/84.jpg",
    trailer: "https://www.youtube.com/results?search_query=Requiem+for+a+Dream+Official+Trailer"
},
{
    rank: 85,
    title: "High and Low",
    year: 1963,
    runtime: 143,
    rating: 8.4,
    genres: ["Crime", "Drama", "Mystery"],
    overview: "A wealthy businessman faces a moral dilemma after a kidnapping goes wrong.",
    poster: "assets/posters/85.jpg",
    trailer: "https://www.youtube.com/results?search_query=High+and+Low+Official+Trailer"
},
{
    rank: 86,
    title: "Capernaum",
    year: 2018,
    runtime: 126,
    rating: 8.4,
    genres: ["Drama"],
    overview: "A neglected boy sues his parents for bringing him into a life of suffering.",
    poster: "assets/posters/86.jpg",
    trailer: "https://www.youtube.com/results?search_query=Capernaum+Official+Trailer"
},
{
    rank: 87,
    title: "Singin' in the Rain",
    year: 1952,
    runtime: 103,
    rating: 8.3,
    genres: ["Comedy", "Musical", "Romance"],
    overview: "Hollywood stars navigate the transition from silent films to talking pictures.",
    poster: "assets/posters/87.jpg",
    trailer: "https://www.youtube.com/results?search_query=Singin+in+the+Rain+Official+Trailer"
},
{
    rank: 88,
    title: "Eternal Sunshine of the Spotless Mind",
    year: 2004,
    runtime: 108,
    rating: 8.3,
    genres: ["Drama", "Romance", "Sci-Fi"],
    overview: "A couple undergoes a procedure to erase memories of their failed relationship.",
    poster: "assets/posters/88.jpg",
    trailer: "https://www.youtube.com/results?search_query=Eternal+Sunshine+of+the+Spotless+Mind+Trailer"
},
{
    rank: 89,
    title: "Come and See",
    year: 1985,
    runtime: 142,
    rating: 8.4,
    genres: ["Drama", "War"],
    overview: "A Belarusian boy experiences the unimaginable horrors of Nazi occupation.",
    poster: "assets/posters/89.jpg",
    trailer: "https://www.youtube.com/results?search_query=Come+and+See+Official+Trailer"
},
{
    rank: 90,
    title: "Toy Story 3",
    year: 2010,
    runtime: 103,
    rating: 8.3,
    genres: ["Animation", "Adventure", "Comedy"],
    overview: "Woody and Buzz face an uncertain future when Andy prepares for college.",
    poster: "assets/posters/90.jpg",
    trailer: "https://www.youtube.com/results?search_query=Toy+Story+3+Official+Trailer"
},
{
    rank: 91,
    title: "Star Wars: Episode VI – Return of the Jedi",
    year: 1983,
    runtime: 131,
    rating: 8.3,
    genres: ["Action", "Adventure", "Fantasy"],
    overview: "Luke confronts Darth Vader as the Rebel Alliance launches its final assault.",
    poster: "assets/posters/91.jpg",
    trailer: "https://www.youtube.com/results?search_query=Return+of+the+Jedi+Official+Trailer"
},
{
    rank: 92,
    title: "Reservoir Dogs",
    year: 1992,
    runtime: 99,
    rating: 8.3,
    genres: ["Crime", "Thriller"],
    overview: "A diamond heist goes disastrously wrong, leaving criminals suspicious of one another.",
    poster: "assets/posters/92.jpg",
    trailer: "https://www.youtube.com/results?search_query=Reservoir+Dogs+Official+Trailer"
},
{
    rank: 93,
    title: "2001: A Space Odyssey",
    year: 1968,
    runtime: 149,
    rating: 8.3,
    genres: ["Adventure", "Sci-Fi"],
    overview: "A mysterious monolith influences humanity's evolution across space and time.",
    poster: "assets/posters/93.jpg",
    trailer: "https://www.youtube.com/results?search_query=2001+A+Space+Odyssey+Official+Trailer"
},
{
    rank: 94,
    title: "Lawrence of Arabia",
    year: 1962,
    runtime: 227,
    rating: 8.3,
    genres: ["Adventure", "Biography", "Drama"],
    overview: "The remarkable story of T.E. Lawrence during the Arab Revolt in World War I.",
    poster: "assets/posters/94.jpg",
    trailer: "https://www.youtube.com/results?search_query=Lawrence+of+Arabia+Official+Trailer"
},
{
    rank: 95,
    title: "The Hunt",
    year: 2012,
    runtime: 115,
    rating: 8.3,
    genres: ["Drama"],
    overview: "A teacher's life is destroyed after a false accusation spreads through his small town.",
    poster: "assets/posters/95.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Hunt+2012+Official+Trailer"
},
{
    rank: 96,
    title: "Oppenheimer",
    year: 2023,
    runtime: 180,
    rating: 8.3,
    genres: ["Biography", "Drama", "History"],
    overview: "The story of J. Robert Oppenheimer and the creation of the atomic bomb.",
    poster: "assets/posters/96.jpg",
    trailer: "https://www.youtube.com/results?search_query=Oppenheimer+Official+Trailer"
},
{
    rank: 97,
    title: "Vertigo",
    year: 1958,
    runtime: 128,
    rating: 8.3,
    genres: ["Mystery", "Romance", "Thriller"],
    overview: "A retired detective becomes obsessed with a mysterious woman he is hired to follow.",
    poster: "assets/posters/97.jpg",
    trailer: "https://www.youtube.com/results?search_query=Vertigo+Official+Trailer"
},
{
    rank: 98,
    title: "M",
    year: 1931,
    runtime: 99,
    rating: 8.3,
    genres: ["Crime", "Mystery", "Thriller"],
    overview: "A child murderer is hunted by both the police and the criminal underworld.",
    poster: "assets/posters/98.jpg",
    trailer: "https://www.youtube.com/results?search_query=M+1931+Official+Trailer"
},
{
    rank: 99,
    title: "Citizen Kane",
    year: 1941,
    runtime: 119,
    rating: 8.3,
    genres: ["Drama", "Mystery"],
    overview: "A reporter investigates the mysterious final word of publishing magnate Charles Foster Kane.",
    poster: "assets/posters/99.jpg",
    trailer: "https://www.youtube.com/results?search_query=Citizen+Kane+Official+Trailer"
},
{
    rank: 100,
    title: "North by Northwest",
    year: 1959,
    runtime: 136,
    rating: 8.3,
    genres: ["Action", "Adventure", "Mystery"],
    overview: "An innocent advertising executive is mistaken for a government agent and pursued across America.",
    poster: "assets/posters/100.jpg",
    trailer: "https://www.youtube.com/results?search_query=North+by+Northwest+Official+Trailer"
},
{
    rank: 101,
    title: "Ikiru",
    year: 1952,
    runtime: 143,
    rating: 8.3,
    genres: ["Drama"],
    overview: "A terminally ill bureaucrat searches for meaning during the final months of his life.",
    poster: "assets/posters/101.jpg",
    trailer: "https://www.youtube.com/results?search_query=Ikiru+Official+Trailer"
},
{
    rank: 102,
    title: "Amélie",
    year: 2001,
    runtime: 122,
    rating: 8.3,
    genres: ["Comedy", "Romance"],
    overview: "A shy Parisian waitress secretly improves the lives of those around her while searching for love.",
    poster: "assets/posters/102.jpg",
    trailer: "https://www.youtube.com/results?search_query=Amelie+Official+Trailer"
},
{
    rank: 103,
    title: "A Clockwork Orange",
    year: 1971,
    runtime: 136,
    rating: 8.3,
    genres: ["Crime", "Drama", "Sci-Fi"],
    overview: "A violent delinquent undergoes an experimental treatment that changes his life forever.",
    poster: "assets/posters/103.jpg",
    trailer: "https://www.youtube.com/results?search_query=A+Clockwork+Orange+Official+Trailer"
},
{
    rank: 104,
    title: "Bicycle Thieves",
    year: 1948,
    runtime: 89,
    rating: 8.3,
    genres: ["Drama"],
    overview: "A poor father desperately searches for his stolen bicycle, essential for his livelihood.",
    poster: "assets/posters/104.jpg",
    trailer: "https://www.youtube.com/results?search_query=Bicycle+Thieves+Official+Trailer"
},
{
    rank: 105,
    title: "Double Indemnity",
    year: 1944,
    runtime: 107,
    rating: 8.3,
    genres: ["Crime", "Drama", "Film-Noir"],
    overview: "An insurance salesman is lured into a deadly murder scheme by a femme fatale.",
    poster: "assets/posters/105.jpg",
    trailer: "https://www.youtube.com/results?search_query=Double+Indemnity+Official+Trailer"
},
{
    rank: 106,
    title: "Full Metal Jacket",
    year: 1987,
    runtime: 116,
    rating: 8.3,
    genres: ["Drama", "War"],
    overview: "A gripping portrayal of U.S. Marines during the Vietnam War.",
    poster: "assets/posters/106.jpg",
    trailer: "https://www.youtube.com/results?search_query=Full+Metal+Jacket+Official+Trailer"
},
{
    rank: 107,
    title: "Scarface",
    year: 1983,
    runtime: 170,
    rating: 8.3,
    genres: ["Crime", "Drama"],
    overview: "A Cuban immigrant rises to power in Miami's drug underworld before his empire collapses.",
    poster: "assets/posters/107.jpg",
    trailer: "https://www.youtube.com/results?search_query=Scarface+1983+Official+Trailer"
},
{
    rank: 108,
    title: "The Apartment",
    year: 1960,
    runtime: 125,
    rating: 8.3,
    genres: ["Comedy", "Drama", "Romance"],
    overview: "An office worker lends his apartment to executives until love changes everything.",
    poster: "assets/posters/108.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Apartment+Official+Trailer"
},
{
    rank: 109,
    title: "Incendies",
    year: 2010,
    runtime: 131,
    rating: 8.3,
    genres: ["Drama", "Mystery", "War"],
    overview: "Twins uncover their mother's tragic past through a journey across the Middle East.",
    poster: "assets/posters/109.jpg",
    trailer: "https://www.youtube.com/results?search_query=Incendies+Official+Trailer"
},
{
    rank: 110,
    title: "Heat",
    year: 1995,
    runtime: 170,
    rating: 8.3,
    genres: ["Action", "Crime", "Drama"],
    overview: "A master thief and an obsessive detective become locked in a deadly game of cat and mouse.",
    poster: "assets/posters/110.jpg",
    trailer: "https://www.youtube.com/results?search_query=Heat+1995+Official+Trailer"
},
{
    rank: 111,
    title: "Up",
    year: 2009,
    runtime: 96,
    rating: 8.3,
    genres: ["Animation", "Adventure", "Comedy"],
    overview: "An elderly widower fulfills his lifelong dream by flying his house to South America.",
    poster: "assets/posters/111.jpg",
    trailer: "https://www.youtube.com/results?search_query=Up+Official+Trailer"
},
{
    rank: 112,
    title: "To Kill a Mockingbird",
    year: 1962,
    runtime: 129,
    rating: 8.3,
    genres: ["Crime", "Drama"],
    overview: "A lawyer defends a Black man falsely accused of a terrible crime in the Deep South.",
    poster: "assets/posters/112.jpg",
    trailer: "https://www.youtube.com/results?search_query=To+Kill+a+Mockingbird+Official+Trailer"
},
{
    rank: 113,
    title: "L.A. Confidential",
    year: 1997,
    runtime: 138,
    rating: 8.2,
    genres: ["Crime", "Drama", "Mystery"],
    overview: "Three very different police officers investigate corruption in 1950s Los Angeles.",
    poster: "assets/posters/113.jpg",
    trailer: "https://www.youtube.com/results?search_query=LA+Confidential+Official+Trailer"
},
{
    rank: 114,
    title: "Die Hard",
    year: 1988,
    runtime: 132,
    rating: 8.2,
    genres: ["Action", "Thriller"],
    overview: "A New York cop battles terrorists inside a Los Angeles skyscraper.",
    poster: "assets/posters/114.jpg",
    trailer: "https://www.youtube.com/results?search_query=Die+Hard+Official+Trailer"
},
{
    rank: 115,
    title: "Green Book",
    year: 2018,
    runtime: 130,
    rating: 8.2,
    genres: ["Biography", "Comedy", "Drama"],
    overview: "A working-class driver becomes the chauffeur for a world-class pianist during a concert tour.",
    poster: "assets/posters/115.jpg",
    trailer: "https://www.youtube.com/results?search_query=Green+Book+Official+Trailer"
},
{
    rank: 116,
    title: "Indiana Jones and the Last Crusade",
    year: 1989,
    runtime: 127,
    rating: 8.2,
    genres: ["Action", "Adventure"],
    overview: "Indiana Jones teams up with his father in search of the Holy Grail.",
    poster: "assets/posters/116.jpg",
    trailer: "https://www.youtube.com/results?search_query=Indiana+Jones+Last+Crusade+Trailer"
},
{
    rank: 117,
    title: "Metropolis",
    year: 1927,
    runtime: 153,
    rating: 8.3,
    genres: ["Drama", "Sci-Fi"],
    overview: "A futuristic city is divided between wealthy elites and oppressed workers.",
    poster: "assets/posters/117.jpg",
    trailer: "https://www.youtube.com/results?search_query=Metropolis+1927+Official+Trailer"
},
{
    rank: 118,
    title: "Snatch",
    year: 2000,
    runtime: 104,
    rating: 8.2,
    genres: ["Comedy", "Crime"],
    overview: "A stolen diamond connects boxers, gangsters and thieves in chaotic London.",
    poster: "assets/posters/118.jpg",
    trailer: "https://www.youtube.com/results?search_query=Snatch+Official+Trailer"
},
{
    rank: 119,
    title: "Hamilton",
    year: 2020,
    runtime: 160,
    rating: 8.3,
    genres: ["Biography", "Drama", "History"],
    overview: "The groundbreaking Broadway musical tells the story of Alexander Hamilton.",
    poster: "assets/posters/119.jpg",
    trailer: "https://www.youtube.com/results?search_query=Hamilton+Official+Trailer"
},
{
    rank: 120,
    title: "Bicycle Thieves",
    year: 1948,
    runtime: 89,
    rating: 8.3,
    genres: ["Drama"],
    overview: "A father and son search desperately through Rome after a bicycle theft changes their lives.",
    poster: "assets/posters/120.jpg",
    trailer: "https://www.youtube.com/results?search_query=Bicycle+Thieves+Official+Trailer"
},
{
    rank: 121,
    title: "Like Stars on Earth (Taare Zameen Par)",
    year: 2007,
    runtime: 165,
    rating: 8.3,
    genres: ["Drama", "Family"],
    overview: "A compassionate teacher helps a dyslexic child discover his extraordinary potential.",
    poster: "assets/posters/121.jpg",
    trailer: "https://www.youtube.com/results?search_query=Taare+Zameen+Par+Official+Trailer"
},
{
    rank: 122,
    title: "1917",
    year: 2019,
    runtime: 119,
    rating: 8.2,
    genres: ["Drama", "War"],
    overview: "Two British soldiers race against time to deliver a life-saving message during World War I.",
    poster: "assets/posters/122.jpg",
    trailer: "https://www.youtube.com/results?search_query=1917+Official+Trailer"
},
{
    rank: 123,
    title: "Downfall",
    year: 2004,
    runtime: 156,
    rating: 8.2,
    genres: ["Biography", "Drama", "History"],
    overview: "The final days of Adolf Hitler unfold inside his Berlin bunker.",
    poster: "assets/posters/123.jpg",
    trailer: "https://www.youtube.com/results?search_query=Downfall+Official+Trailer"
},
{
    rank: 124,
    title: "Dangal",
    year: 2016,
    runtime: 161,
    rating: 8.3,
    genres: ["Action", "Biography", "Drama"],
    overview: "A former wrestler trains his daughters to become world-class wrestling champions.",
    poster: "assets/posters/124.jpg",
    trailer: "https://www.youtube.com/results?search_query=Dangal+Official+Trailer"
},
{
    rank: 125,
    title: "The Wolf of Wall Street",
    year: 2013,
    runtime: 180,
    rating: 8.2,
    genres: ["Biography", "Comedy", "Crime"],
    overview: "The rise and fall of stockbroker Jordan Belfort in a world of excess and corruption.",
    poster: "assets/posters/125.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Wolf+of+Wall+Street+Official+Trailer"
},
{
    rank: 126,
    title: "Batman Begins",
    year: 2005,
    runtime: 140,
    rating: 8.2,
    genres: ["Action", "Crime", "Drama"],
    overview: "Bruce Wayne returns to Gotham to become Batman and battle corruption.",
    poster: "assets/posters/126.jpg",
    trailer: "https://www.youtube.com/results?search_query=Batman+Begins+Official+Trailer"
},
{
    rank: 127,
    title: "Some Like It Hot",
    year: 1959,
    runtime: 121,
    rating: 8.2,
    genres: ["Comedy", "Music", "Romance"],
    overview: "Two musicians disguise themselves as women after witnessing a mob crime.",
    poster: "assets/posters/127.jpg",
    trailer: "https://www.youtube.com/results?search_query=Some+Like+It+Hot+Official+Trailer"
},
{
    rank: 128,
    title: "Unforgiven",
    year: 1992,
    runtime: 130,
    rating: 8.2,
    genres: ["Drama", "Western"],
    overview: "A retired gunslinger takes one last bounty hunting job.",
    poster: "assets/posters/128.jpg",
    trailer: "https://www.youtube.com/results?search_query=Unforgiven+Official+Trailer"
},
{
    rank: 129,
    title: "The Kid",
    year: 1921,
    runtime: 68,
    rating: 8.2,
    genres: ["Comedy", "Drama", "Family"],
    overview: "Charlie Chaplin's Tramp raises an abandoned child in this timeless classic.",
    poster: "assets/posters/129.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Kid+1921+Trailer"
},
{
    rank: 130,
    title: "Judgment at Nuremberg",
    year: 1961,
    runtime: 179,
    rating: 8.3,
    genres: ["Drama", "War"],
    overview: "American judges preside over the trials of Nazi officials after World War II.",
    poster: "assets/posters/130.jpg",
    trailer: "https://www.youtube.com/results?search_query=Judgment+at+Nuremberg+Trailer"
},
{
    rank: 131,
    title: "All About Eve",
    year: 1950,
    runtime: 138,
    rating: 8.2,
    genres: ["Drama"],
    overview: "A young admirer manipulates her way into the life of a celebrated actress.",
    poster: "assets/posters/131.jpg",
    trailer: "https://www.youtube.com/results?search_query=All+About+Eve+Official+Trailer"
},
{
    rank: 132,
    title: "The Truman Show",
    year: 1998,
    runtime: 103,
    rating: 8.2,
    genres: ["Comedy", "Drama", "Sci-Fi"],
    overview: "A man slowly discovers his entire life is actually a televised reality show.",
    poster: "assets/posters/132.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Truman+Show+Official+Trailer"
},
{
    rank: 133,
    title: "There Will Be Blood",
    year: 2007,
    runtime: 158,
    rating: 8.2,
    genres: ["Drama"],
    overview: "An ambitious oilman sacrifices everything in his relentless pursuit of wealth.",
    poster: "assets/posters/133.jpg",
    trailer: "https://www.youtube.com/results?search_query=There+Will+Be+Blood+Official+Trailer"
},
{
    rank: 134,
    title: "The Sixth Sense",
    year: 1999,
    runtime: 107,
    rating: 8.2,
    genres: ["Drama", "Mystery", "Thriller"],
    overview: "A troubled boy who sees dead people seeks help from a child psychologist.",
    poster: "assets/posters/134.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Sixth+Sense+Official+Trailer"
},
{
    rank: 135,
    title: "Yojimbo",
    year: 1961,
    runtime: 110,
    rating: 8.2,
    genres: ["Action", "Drama"],
    overview: "A wandering samurai manipulates two rival gangs to destroy each other.",
    poster: "assets/posters/135.jpg",
    trailer: "https://www.youtube.com/results?search_query=Yojimbo+Official+Trailer"
},
{
    rank: 136,
    title: "The Treasure of the Sierra Madre",
    year: 1948,
    runtime: 126,
    rating: 8.2,
    genres: ["Adventure", "Drama", "Western"],
    overview: "Three prospectors discover that greed can be more dangerous than nature.",
    poster: "assets/posters/136.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Treasure+of+the+Sierra+Madre+Trailer"
},
{
    rank: 137,
    title: "Ran",
    year: 1985,
    runtime: 162,
    rating: 8.2,
    genres: ["Action", "Drama", "War"],
    overview: "An aging warlord's decision to divide his kingdom leads to betrayal and tragedy.",
    poster: "assets/posters/137.jpg",
    trailer: "https://www.youtube.com/results?search_query=Ran+1985+Official+Trailer"
},
{
    rank: 138,
    title: "Pan's Labyrinth",
    year: 2006,
    runtime: 118,
    rating: 8.2,
    genres: ["Drama", "Fantasy", "War"],
    overview: "A young girl escapes into a mythical world during post-Civil War Spain.",
    poster: "assets/posters/138.jpg",
    trailer: "https://www.youtube.com/results?search_query=Pans+Labyrinth+Official+Trailer"
},
{
    rank: 139,
    title: "Casino",
    year: 1995,
    runtime: 178,
    rating: 8.2,
    genres: ["Crime", "Drama"],
    overview: "The rise and fall of a casino empire in Las Vegas under Mafia control.",
    poster: "assets/posters/139.jpg",
    trailer: "https://www.youtube.com/results?search_query=Casino+1995+Official+Trailer"
},
{
    rank: 140,
    title: "A Beautiful Mind",
    year: 2001,
    runtime: 135,
    rating: 8.2,
    genres: ["Biography", "Drama"],
    overview: "The life of brilliant mathematician John Nash and his battle with schizophrenia.",
    poster: "assets/posters/140.jpg",
    trailer: "https://www.youtube.com/results?search_query=A+Beautiful+Mind+Official+Trailer"
},
{
    rank: 141,
    title: "Shutter Island",
    year: 2010,
    runtime: 138,
    rating: 8.2,
    genres: ["Mystery", "Thriller"],
    overview: "A U.S. Marshal investigates the disappearance of a patient from a remote asylum.",
    poster: "assets/posters/141.jpg",
    trailer: "https://www.youtube.com/results?search_query=Shutter+Island+Official+Trailer"
},
{
    rank: 142,
    title: "The Great Escape",
    year: 1963,
    runtime: 172,
    rating: 8.2,
    genres: ["Adventure", "Drama", "War"],
    overview: "Allied prisoners plan an ambitious escape from a German POW camp.",
    poster: "assets/posters/142.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Great+Escape+Official+Trailer"
},
{
    rank: 143,
    title: "Lock, Stock and Two Smoking Barrels",
    year: 1998,
    runtime: 107,
    rating: 8.2,
    genres: ["Comedy", "Crime"],
    overview: "Four friends become entangled with gangsters after a high-stakes poker game.",
    poster: "assets/posters/143.jpg",
    trailer: "https://www.youtube.com/results?search_query=Lock+Stock+and+Two+Smoking+Barrels+Trailer"
},
{
    rank: 144,
    title: "Jurassic Park",
    year: 1993,
    runtime: 127,
    rating: 8.2,
    genres: ["Adventure", "Sci-Fi"],
    overview: "Scientists and visitors struggle to survive after cloned dinosaurs escape.",
    poster: "assets/posters/144.jpg",
    trailer: "https://www.youtube.com/results?search_query=Jurassic+Park+Official+Trailer"
},
{
    rank: 145,
    title: "No Country for Old Men",
    year: 2007,
    runtime: 122,
    rating: 8.2,
    genres: ["Crime", "Drama", "Thriller"],
    overview: "A hunter discovers drug money and becomes the target of a ruthless killer.",
    poster: "assets/posters/145.jpg",
    trailer: "https://www.youtube.com/results?search_query=No+Country+for+Old+Men+Official+Trailer"
},
{
    rank: 146,
    title: "The Elephant Man",
    year: 1980,
    runtime: 124,
    rating: 8.2,
    genres: ["Biography", "Drama"],
    overview: "A severely disfigured man finds compassion and dignity in Victorian England.",
    poster: "assets/posters/146.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Elephant+Man+Official+Trailer"
},
{
    rank: 147,
    title: "The Secret in Their Eyes (El secreto de sus ojos)",
    year: 2009,
    runtime: 129,
    rating: 8.2,
    genres: ["Drama", "Mystery", "Romance"],
    overview: "A retired legal counselor revisits an unsolved murder that changed his life.",
    poster: "assets/posters/147.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Secret+in+Their+Eyes+Official+Trailer"
},
{
    rank: 148,
    title: "Inside Out",
    year: 2015,
    runtime: 95,
    rating: 8.1,
    genres: ["Animation", "Adventure", "Comedy"],
    overview: "The emotions inside a young girl's mind guide her through a major life change.",
    poster: "assets/posters/148.jpg",
    trailer: "https://www.youtube.com/results?search_query=Inside+Out+Official+Trailer"
},
{
    rank: 149,
    title: "Raging Bull",
    year: 1980,
    runtime: 129,
    rating: 8.2,
    genres: ["Biography", "Drama", "Sport"],
    overview: "The turbulent life and career of boxer Jake LaMotta.",
    poster: "assets/posters/149.jpg",
    trailer: "https://www.youtube.com/results?search_query=Raging+Bull+Official+Trailer"
},
{
    rank: 150,
    title: "The Bridge on the River Kwai",
    year: 1957,
    runtime: 161,
    rating: 8.2,
    genres: ["Adventure", "Drama", "War"],
    overview: "British POWs are forced to build a bridge for the Japanese during World War II.",
    poster: "assets/posters/150.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Bridge+on+the+River+Kwai+Official+Trailer"
},
{
    rank: 151,
    title: "Chinatown",
    year: 1974,
    runtime: 130,
    rating: 8.2,
    genres: ["Drama", "Mystery", "Thriller"],
    overview: "A private detective uncovers corruption and family secrets while investigating a seemingly simple case.",
    poster: "assets/posters/151.jpg",
    trailer: "https://www.youtube.com/results?search_query=Chinatown+Official+Trailer"
},
{
    rank: 152,
    title: "Dial M for Murder",
    year: 1954,
    runtime: 105,
    rating: 8.2,
    genres: ["Crime", "Thriller"],
    overview: "A former tennis player plots the perfect murder of his wealthy wife.",
    poster: "assets/posters/152.jpg",
    trailer: "https://www.youtube.com/results?search_query=Dial+M+for+Murder+Official+Trailer"
},
{
    rank: 153,
    title: "Three Billboards Outside Ebbing, Missouri",
    year: 2017,
    runtime: 115,
    rating: 8.1,
    genres: ["Comedy", "Crime", "Drama"],
    overview: "A grieving mother challenges local police after her daughter's murder remains unsolved.",
    poster: "assets/posters/153.jpg",
    trailer: "https://www.youtube.com/results?search_query=Three+Billboards+Outside+Ebbing+Missouri+Trailer"
},
{
    rank: 154,
    title: "V for Vendetta",
    year: 2005,
    runtime: 132,
    rating: 8.2,
    genres: ["Action", "Drama", "Sci-Fi"],
    overview: "A masked vigilante inspires a revolution against a totalitarian government.",
    poster: "assets/posters/154.jpg",
    trailer: "https://www.youtube.com/results?search_query=V+for+Vendetta+Official+Trailer"
},
{
    rank: 155,
    title: "Trainspotting",
    year: 1996,
    runtime: 94,
    rating: 8.1,
    genres: ["Drama"],
    overview: "A group of heroin addicts struggle with addiction and friendship in Edinburgh.",
    poster: "assets/posters/155.jpg",
    trailer: "https://www.youtube.com/results?search_query=Trainspotting+Official+Trailer"
},
{
    rank: 156,
    title: "Fargo",
    year: 1996,
    runtime: 98,
    rating: 8.1,
    genres: ["Crime", "Drama", "Thriller"],
    overview: "A desperate man's kidnapping scheme spirals into chaos and murder.",
    poster: "assets/posters/156.jpg",
    trailer: "https://www.youtube.com/results?search_query=Fargo+Official+Trailer"
},
{
    rank: 157,
    title: "Warrior",
    year: 2011,
    runtime: 140,
    rating: 8.2,
    genres: ["Action", "Drama", "Sport"],
    overview: "Two estranged brothers meet in a high-stakes mixed martial arts tournament.",
    poster: "assets/posters/157.jpg",
    trailer: "https://www.youtube.com/results?search_query=Warrior+2011+Official+Trailer"
},
{
    rank: 158,
    title: "Gone Girl",
    year: 2014,
    runtime: 149,
    rating: 8.1,
    genres: ["Drama", "Mystery", "Thriller"],
    overview: "A man becomes the prime suspect after his wife mysteriously disappears.",
    poster: "assets/posters/158.jpg",
    trailer: "https://www.youtube.com/results?search_query=Gone+Girl+Official+Trailer"
},
{
    rank: 159,
    title: "The Thing",
    year: 1982,
    runtime: 109,
    rating: 8.2,
    genres: ["Horror", "Mystery", "Sci-Fi"],
    overview: "Scientists in Antarctica battle a terrifying shape-shifting alien organism.",
    poster: "assets/posters/159.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Thing+1982+Official+Trailer"
},
{
    rank: 160,
    title: "Klaus",
    year: 2019,
    runtime: 96,
    rating: 8.2,
    genres: ["Animation", "Adventure", "Comedy"],
    overview: "A selfish postman discovers the true meaning of kindness in a remote town.",
    poster: "assets/posters/160.jpg",
    trailer: "https://www.youtube.com/results?search_query=Klaus+Official+Trailer"
},
{
    rank: 161,
    title: "Finding Nemo",
    year: 2003,
    runtime: 100,
    rating: 8.2,
    genres: ["Animation", "Adventure", "Comedy"],
    overview: "A clownfish crosses the ocean to rescue his captured son.",
    poster: "assets/posters/161.jpg",
    trailer: "https://www.youtube.com/results?search_query=Finding+Nemo+Official+Trailer"
},
{
    rank: 162,
    title: "On the Waterfront",
    year: 1954,
    runtime: 108,
    rating: 8.1,
    genres: ["Crime", "Drama", "Thriller"],
    overview: "A dockworker stands up against corruption controlled by the local mob.",
    poster: "assets/posters/162.jpg",
    trailer: "https://www.youtube.com/results?search_query=On+the+Waterfront+Official+Trailer"
},
{
    rank: 163,
    title: "Prisoners",
    year: 2013,
    runtime: 153,
    rating: 8.2,
    genres: ["Crime", "Drama", "Mystery"],
    overview: "A father takes desperate measures after his daughter disappears.",
    poster: "assets/posters/163.jpg",
    trailer: "https://www.youtube.com/results?search_query=Prisoners+Official+Trailer"
},
{
    rank: 164,
    title: "The Third Man",
    year: 1949,
    runtime: 104,
    rating: 8.1,
    genres: ["Film-Noir", "Mystery", "Thriller"],
    overview: "An American writer investigates the mysterious death of a friend in postwar Vienna.",
    poster: "assets/posters/164.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Third+Man+Official+Trailer"
},
{
    rank: 165,
    title: "Gran Torino",
    year: 2008,
    runtime: 116,
    rating: 8.1,
    genres: ["Drama"],
    overview: "A bitter war veteran forms an unlikely friendship with his immigrant neighbors.",
    poster: "assets/posters/165.jpg",
    trailer: "https://www.youtube.com/results?search_query=Gran+Torino+Official+Trailer"
},
{
    rank: 166,
    title: "Wild Tales (Relatos salvajes)",
    year: 2014,
    runtime: 122,
    rating: 8.1,
    genres: ["Comedy", "Drama", "Thriller"],
    overview: "Six darkly humorous stories explore revenge, justice and human nature.",
    poster: "assets/posters/166.jpg",
    trailer: "https://www.youtube.com/results?search_query=Wild+Tales+Official+Trailer"
},
{
    rank: 167,
    title: "Mary and Max",
    year: 2009,
    runtime: 92,
    rating: 8.1,
    genres: ["Animation", "Comedy", "Drama"],
    overview: "A heartfelt friendship develops between a lonely Australian girl and a man in New York.",
    poster: "assets/posters/167.jpg",
    trailer: "https://www.youtube.com/results?search_query=Mary+and+Max+Official+Trailer"
},
{
    rank: 168,
    title: "The Gold Rush",
    year: 1925,
    runtime: 95,
    rating: 8.1,
    genres: ["Adventure", "Comedy", "Drama"],
    overview: "The Little Tramp searches for fortune during the Klondike Gold Rush.",
    poster: "assets/posters/168.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Gold+Rush+Official+Trailer"
},
{
    rank: 169,
    title: "Blade Runner",
    year: 1982,
    runtime: 117,
    rating: 8.1,
    genres: ["Action", "Drama", "Sci-Fi"],
    overview: "A blade runner hunts bioengineered replicants in a dystopian future.",
    poster: "assets/posters/169.jpg",
    trailer: "https://www.youtube.com/results?search_query=Blade+Runner+Official+Trailer"
},
{
    rank: 170,
    title: "Before Sunrise",
    year: 1995,
    runtime: 101,
    rating: 8.1,
    genres: ["Drama", "Romance"],
    overview: "Two strangers spend one unforgettable night together wandering through Vienna.",
    poster: "assets/posters/170.jpg",
    trailer: "https://www.youtube.com/results?search_query=Before+Sunrise+Official+Trailer"
},
{
    rank: 171,
    title: "In the Name of the Father",
    year: 1993,
    runtime: 133,
    rating: 8.1,
    genres: ["Biography", "Crime", "Drama"],
    overview: "An innocent man fights to clear his name after being wrongly imprisoned.",
    poster: "assets/posters/171.jpg",
    trailer: "https://www.youtube.com/results?search_query=In+the+Name+of+the+Father+Trailer"
},
{
    rank: 172,
    title: "The General",
    year: 1926,
    runtime: 78,
    rating: 8.1,
    genres: ["Action", "Adventure", "Comedy"],
    overview: "A railroad engineer pursues his stolen locomotive during the American Civil War.",
    poster: "assets/posters/172.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+General+1926+Trailer"
},
{
    rank: 173,
    title: "Persona",
    year: 1966,
    runtime: 83,
    rating: 8.1,
    genres: ["Drama", "Thriller"],
    overview: "A nurse caring for a silent actress begins to lose her own sense of identity.",
    poster: "assets/posters/173.jpg",
    trailer: "https://www.youtube.com/results?search_query=Persona+1966+Official+Trailer"
},
{
    rank: 174,
    title: "Catch Me If You Can",
    year: 2002,
    runtime: 141,
    rating: 8.1,
    genres: ["Biography", "Crime", "Drama"],
    overview: "A brilliant con artist stays one step ahead of the FBI through deception and charm.",
    poster: "assets/posters/174.jpg",
    trailer: "https://www.youtube.com/results?search_query=Catch+Me+If+You+Can+Official+Trailer"
},
{
    rank: 175,
    title: "Sherlock Jr.",
    year: 1924,
    runtime: 45,
    rating: 8.2,
    genres: ["Action", "Comedy", "Romance"],
    overview: "A projectionist dreams himself into a movie and becomes the detective hero.",
    poster: "assets/posters/175.jpg",
    trailer: "https://www.youtube.com/results?search_query=Sherlock+Jr+Official+Trailer"
},
{
    rank: 176,
    title: "Barry Lyndon",
    year: 1975,
    runtime: 185,
    rating: 8.1,
    genres: ["Adventure", "Drama", "War"],
    overview: "An ambitious Irishman rises through 18th-century European society before his fortunes decline.",
    poster: "assets/posters/176.jpg",
    trailer: "https://www.youtube.com/results?search_query=Barry+Lyndon+Official+Trailer"
},
{
    rank: 177,
    title: "The Deer Hunter",
    year: 1978,
    runtime: 183,
    rating: 8.1,
    genres: ["Drama", "War"],
    overview: "The Vietnam War profoundly changes the lives of three lifelong friends.",
    poster: "assets/posters/177.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Deer+Hunter+Official+Trailer"
},
{
    rank: 178,
    title: "The Grand Budapest Hotel",
    year: 2014,
    runtime: 99,
    rating: 8.1,
    genres: ["Adventure", "Comedy", "Crime"],
    overview: "A legendary concierge and his protégé become entangled in a priceless inheritance mystery.",
    poster: "assets/posters/178.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Grand+Budapest+Hotel+Official+Trailer"
},
{
    rank: 179,
    title: "Hacksaw Ridge",
    year: 2016,
    runtime: 139,
    rating: 8.1,
    genres: ["Biography", "Drama", "War"],
    overview: "A conscientious objector saves dozens of soldiers during one of WWII's bloodiest battles.",
    poster: "assets/posters/179.jpg",
    trailer: "https://www.youtube.com/results?search_query=Hacksaw+Ridge+Official+Trailer"
},
{
    rank: 180,
    title: "Room",
    year: 2015,
    runtime: 118,
    rating: 8.1,
    genres: ["Drama", "Thriller"],
    overview: "A young mother and her son escape captivity and begin a new life.",
    poster: "assets/posters/180.jpg",
    trailer: "https://www.youtube.com/results?search_query=Room+2015+Official+Trailer"
},
{
    rank: 181,
    title: "Howl's Moving Castle",
    year: 2004,
    runtime: 119,
    rating: 8.2,
    genres: ["Animation", "Adventure", "Fantasy"],
    overview: "A young woman cursed with old age seeks refuge in the magical moving castle of a wizard.",
    poster: "assets/posters/181.jpg",
    trailer: "https://www.youtube.com/results?search_query=Howls+Moving+Castle+Official+Trailer"
},
{
    rank: 182,
    title: "The Big Lebowski",
    year: 1998,
    runtime: 117,
    rating: 8.1,
    genres: ["Comedy", "Crime"],
    overview: "A laid-back bowler becomes caught in a bizarre kidnapping scheme.",
    poster: "assets/posters/182.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Big+Lebowski+Official+Trailer"
},
{
    rank: 183,
    title: "To Be or Not to Be",
    year: 1942,
    runtime: 99,
    rating: 8.2,
    genres: ["Comedy", "War"],
    overview: "A Polish acting troupe uses disguises to outwit occupying Nazis.",
    poster: "assets/posters/183.jpg",
    trailer: "https://www.youtube.com/results?search_query=To+Be+or+Not+to+Be+1942+Trailer"
},
{
    rank: 184,
    title: "Ford v Ferrari",
    year: 2019,
    runtime: 152,
    rating: 8.1,
    genres: ["Action", "Biography", "Drama"],
    overview: "American engineers and drivers attempt to defeat Ferrari at Le Mans.",
    poster: "assets/posters/184.jpg",
    trailer: "https://www.youtube.com/results?search_query=Ford+v+Ferrari+Official+Trailer"
},
{
    rank: 185,
    title: "Mad Max: Fury Road",
    year: 2015,
    runtime: 120,
    rating: 8.1,
    genres: ["Action", "Adventure", "Sci-Fi"],
    overview: "Max joins Furiosa in a relentless escape across a post-apocalyptic wasteland.",
    poster: "assets/posters/185.jpg",
    trailer: "https://www.youtube.com/results?search_query=Mad+Max+Fury+Road+Official+Trailer"
},
{
    rank: 186,
    title: "The Wages of Fear",
    year: 1953,
    runtime: 156,
    rating: 8.2,
    genres: ["Adventure", "Drama", "Thriller"],
    overview: "Four desperate men transport volatile explosives across dangerous terrain.",
    poster: "assets/posters/186.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Wages+of+Fear+Official+Trailer"
},
{
    rank: 187,
    title: "Mr. Smith Goes to Washington",
    year: 1939,
    runtime: 129,
    rating: 8.1,
    genres: ["Comedy", "Drama"],
    overview: "An idealistic senator battles corruption in the U.S. government.",
    poster: "assets/posters/187.jpg",
    trailer: "https://www.youtube.com/results?search_query=Mr+Smith+Goes+to+Washington+Trailer"
},
{
    rank: 188,
    title: "Ratatouille",
    year: 2007,
    runtime: 111,
    rating: 8.1,
    genres: ["Animation", "Adventure", "Comedy"],
    overview: "A talented rat pursues his dream of becoming a chef in Paris.",
    poster: "assets/posters/188.jpg",
    trailer: "https://www.youtube.com/results?search_query=Ratatouille+Official+Trailer"
},
{
    rank: 189,
    title: "Tokyo Story",
    year: 1953,
    runtime: 136,
    rating: 8.1,
    genres: ["Drama"],
    overview: "An elderly couple visits their grown children and realizes how life has changed.",
    poster: "assets/posters/189.jpg",
    trailer: "https://www.youtube.com/results?search_query=Tokyo+Story+Official+Trailer"
},
{
    rank: 190,
    title: "Hotel Rwanda",
    year: 2004,
    runtime: 121,
    rating: 8.1,
    genres: ["Biography", "Drama", "History"],
    overview: "A hotel manager shelters hundreds during the Rwandan genocide.",
    poster: "assets/posters/190.jpg",
    trailer: "https://www.youtube.com/results?search_query=Hotel+Rwanda+Official+Trailer"
},
{
    rank: 191,
    title: "Logan",
    year: 2017,
    runtime: 137,
    rating: 8.1,
    genres: ["Action", "Drama", "Sci-Fi"],
    overview: "An aging Wolverine protects a young mutant while confronting his past.",
    poster: "assets/posters/191.jpg",
    trailer: "https://www.youtube.com/results?search_query=Logan+Official+Trailer"
},
{
    rank: 192,
    title: "Dead Poets Society",
    year: 1989,
    runtime: 128,
    rating: 8.1,
    genres: ["Comedy", "Drama"],
    overview: "An inspiring English teacher encourages his students to seize the day.",
    poster: "assets/posters/192.jpg",
    trailer: "https://www.youtube.com/results?search_query=Dead+Poets+Society+Official+Trailer"
},
{
    rank: 193,
    title: "Spotlight",
    year: 2015,
    runtime: 129,
    rating: 8.1,
    genres: ["Biography", "Crime", "Drama"],
    overview: "Investigative journalists expose widespread abuse and institutional cover-ups.",
    poster: "assets/posters/193.jpg",
    trailer: "https://www.youtube.com/results?search_query=Spotlight+Official+Trailer"
},
{
    rank: 194,
    title: "The Passion of Joan of Arc",
    year: 1928,
    runtime: 114,
    rating: 8.1,
    genres: ["Biography", "Drama", "History"],
    overview: "A silent masterpiece depicting the trial of Joan of Arc.",
    poster: "assets/posters/194.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Passion+of+Joan+of+Arc+Trailer"
},
{
    rank: 195,
    title: "Platoon",
    year: 1986,
    runtime: 120,
    rating: 8.1,
    genres: ["Drama", "War"],
    overview: "A young American soldier experiences the brutal realities of the Vietnam War.",
    poster: "assets/posters/195.jpg",
    trailer: "https://www.youtube.com/results?search_query=Platoon+Official+Trailer"
},
{
    rank: 196,
    title: "Rush",
    year: 2013,
    runtime: 123,
    rating: 8.1,
    genres: ["Action", "Biography", "Drama"],
    overview: "The fierce Formula One rivalry between James Hunt and Niki Lauda.",
    poster: "assets/posters/196.jpg",
    trailer: "https://www.youtube.com/results?search_query=Rush+2013+Official+Trailer"
},
{
    rank: 197,
    title: "Stand by Me",
    year: 1986,
    runtime: 89,
    rating: 8.1,
    genres: ["Adventure", "Drama"],
    overview: "Four boys embark on a journey that changes their lives forever.",
    poster: "assets/posters/197.jpg",
    trailer: "https://www.youtube.com/results?search_query=Stand+by+Me+Official+Trailer"
},
{
    rank: 198,
    title: "Network",
    year: 1976,
    runtime: 121,
    rating: 8.1,
    genres: ["Drama"],
    overview: "A television anchor's emotional breakdown becomes a media sensation.",
    poster: "assets/posters/198.jpg",
    trailer: "https://www.youtube.com/results?search_query=Network+1976+Official+Trailer"
},
{
    rank: 199,
    title: "Into the Wild",
    year: 2007,
    runtime: 148,
    rating: 8.1,
    genres: ["Adventure", "Biography", "Drama"],
    overview: "A young graduate abandons society to seek freedom in the Alaskan wilderness.",
    poster: "assets/posters/199.jpg",
    trailer: "https://www.youtube.com/results?search_query=Into+the+Wild+Official+Trailer"
},
{
    rank: 200,
    title: "The Wizard of Oz",
    year: 1939,
    runtime: 102,
    rating: 8.1,
    genres: ["Adventure", "Family", "Fantasy"],
    overview: "Dorothy journeys through the magical Land of Oz in search of home.",
    poster: "assets/posters/200.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Wizard+of+Oz+Official+Trailer"
},
{
    rank: 201,
    title: "The Exorcist",
    year: 1973,
    runtime: 122,
    rating: 8.1,
    genres: ["Horror"],
    overview: "Two priests attempt to save a young girl believed to be possessed by a demonic force.",
    poster: "assets/posters/201.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Exorcist+Official+Trailer"
},
{
    rank: 202,
    title: "Groundhog Day",
    year: 1993,
    runtime: 101,
    rating: 8.0,
    genres: ["Comedy", "Drama", "Fantasy"],
    overview: "A cynical weatherman relives the same day repeatedly until he changes his life.",
    poster: "assets/posters/202.jpg",
    trailer: "https://www.youtube.com/results?search_query=Groundhog+Day+Official+Trailer"
},
{
    rank: 203,
    title: "The Best Years of Our Lives",
    year: 1946,
    runtime: 170,
    rating: 8.1,
    genres: ["Drama", "Romance", "War"],
    overview: "Three World War II veterans return home and struggle to readjust to civilian life.",
    poster: "assets/posters/203.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Best+Years+of+Our+Lives+Trailer"
},
{
    rank: 204,
    title: "The Incredibles",
    year: 2004,
    runtime: 115,
    rating: 8.0,
    genres: ["Animation", "Action", "Adventure"],
    overview: "A family of superheroes returns to action to save the world from a dangerous villain.",
    poster: "assets/posters/204.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Incredibles+Official+Trailer"
},
{
    rank: 205,
    title: "Before Sunset",
    year: 2004,
    runtime: 80,
    rating: 8.1,
    genres: ["Drama", "Romance"],
    overview: "Nine years after their first meeting, Jesse and Céline reunite in Paris.",
    poster: "assets/posters/205.jpg",
    trailer: "https://www.youtube.com/results?search_query=Before+Sunset+Official+Trailer"
},
{
    rank: 206,
    title: "The Grapes of Wrath",
    year: 1940,
    runtime: 129,
    rating: 8.1,
    genres: ["Drama"],
    overview: "A struggling family travels west during the Great Depression seeking a better future.",
    poster: "assets/posters/206.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Grapes+of+Wrath+Official+Trailer"
},
{
    rank: 207,
    title: "Hachi: A Dog's Tale",
    year: 2009,
    runtime: 93,
    rating: 8.1,
    genres: ["Drama", "Family"],
    overview: "The touching true story of an incredibly loyal dog who waits years for his owner.",
    poster: "assets/posters/207.jpg",
    trailer: "https://www.youtube.com/results?search_query=Hachi+A+Dogs+Tale+Official+Trailer"
},
{
    rank: 208,
    title: "Rebecca",
    year: 1940,
    runtime: 130,
    rating: 8.1,
    genres: ["Drama", "Mystery", "Romance"],
    overview: "A newly married woman struggles under the shadow of her husband's late wife.",
    poster: "assets/posters/208.jpg",
    trailer: "https://www.youtube.com/results?search_query=Rebecca+1940+Official+Trailer"
},
{
    rank: 209,
    title: "Cool Hand Luke",
    year: 1967,
    runtime: 127,
    rating: 8.1,
    genres: ["Crime", "Drama"],
    overview: "A rebellious prisoner refuses to conform inside a brutal prison camp.",
    poster: "assets/posters/209.jpg",
    trailer: "https://www.youtube.com/results?search_query=Cool+Hand+Luke+Official+Trailer"
},
{
    rank: 210,
    title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    year: 2003,
    runtime: 143,
    rating: 8.1,
    genres: ["Action", "Adventure", "Fantasy"],
    overview: "Captain Jack Sparrow joins forces with a blacksmith to rescue a kidnapped governor's daughter.",
    poster: "assets/posters/210.jpg",
    trailer: "https://www.youtube.com/results?search_query=Pirates+of+the+Caribbean+Black+Pearl+Trailer"
},
{
    rank: 211,
    title: "La Haine",
    year: 1995,
    runtime: 98,
    rating: 8.1,
    genres: ["Crime", "Drama"],
    overview: "Twenty-four tense hours unfold after riots erupt in the suburbs of Paris.",
    poster: "assets/posters/211.jpg",
    trailer: "https://www.youtube.com/results?search_query=La+Haine+Official+Trailer"
},
{
    rank: 212,
    title: "The Sound of Music",
    year: 1965,
    runtime: 172,
    rating: 8.1,
    genres: ["Biography", "Drama", "Family"],
    overview: "A young governess brings joy and music to the children of an Austrian naval officer.",
    poster: "assets/posters/212.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Sound+of+Music+Official+Trailer"
},
{
    rank: 213,
    title: "The Help",
    year: 2011,
    runtime: 146,
    rating: 8.1,
    genres: ["Drama"],
    overview: "A young writer documents the lives of African-American maids in 1960s Mississippi.",
    poster: "assets/posters/213.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Help+Official+Trailer"
},
{
    rank: 214,
    title: "It Happened One Night",
    year: 1934,
    runtime: 105,
    rating: 8.1,
    genres: ["Comedy", "Romance"],
    overview: "A runaway heiress and a newspaper reporter embark on an unforgettable journey.",
    poster: "assets/posters/214.jpg",
    trailer: "https://www.youtube.com/results?search_query=It+Happened+One+Night+Official+Trailer"
},
{
    rank: 215,
    title: "Aladdin",
    year: 1992,
    runtime: 90,
    rating: 8.0,
    genres: ["Animation", "Adventure", "Comedy"],
    overview: "A street thief discovers a magical lamp that changes his destiny forever.",
    poster: "assets/posters/215.jpg",
    trailer: "https://www.youtube.com/results?search_query=Aladdin+1992+Official+Trailer"
},
{
    rank: 216,
    title: "Dersu Uzala",
    year: 1975,
    runtime: 144,
    rating: 8.2,
    genres: ["Adventure", "Biography", "Drama"],
    overview: "A Russian explorer forms a lasting friendship with a skilled hunter in Siberia.",
    poster: "assets/posters/216.jpg",
    trailer: "https://www.youtube.com/results?search_query=Dersu+Uzala+Official+Trailer"
},
{
    rank: 217,
    title: "Gandhi",
    year: 1982,
    runtime: 191,
    rating: 8.0,
    genres: ["Biography", "Drama", "History"],
    overview: "The life and legacy of Mahatma Gandhi and India's struggle for independence.",
    poster: "assets/posters/217.jpg",
    trailer: "https://www.youtube.com/results?search_query=Gandhi+Official+Trailer"
},
{
    rank: 218,
    title: "The Iron Giant",
    year: 1999,
    runtime: 86,
    rating: 8.1,
    genres: ["Animation", "Action", "Adventure"],
    overview: "A young boy befriends a giant robot from outer space.",
    poster: "assets/posters/218.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Iron+Giant+Official+Trailer"
},
{
    rank: 219,
    title: "The Handmaiden",
    year: 2016,
    runtime: 145,
    rating: 8.1,
    genres: ["Drama", "Romance", "Thriller"],
    overview: "A con artist's elaborate scheme becomes increasingly complicated by love and betrayal.",
    poster: "assets/posters/219.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Handmaiden+Official+Trailer"
},
{
    rank: 220,
    title: "Paris, Texas",
    year: 1984,
    runtime: 145,
    rating: 8.1,
    genres: ["Drama"],
    overview: "A drifter attempts to reconnect with his young son and estranged wife.",
    poster: "assets/posters/220.jpg",
    trailer: "https://www.youtube.com/results?search_query=Paris+Texas+Official+Trailer"
},
{
    rank: 221,
    title: "The 400 Blows",
    year: 1959,
    runtime: 99,
    rating: 8.1,
    genres: ["Crime", "Drama"],
    overview: "A neglected Parisian boy turns to petty crime while searching for freedom.",
    poster: "assets/posters/221.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+400+Blows+Official+Trailer"
},
{
    rank: 222,
    title: "Life of Brian",
    year: 1979,
    runtime: 94,
    rating: 8.0,
    genres: ["Comedy"],
    overview: "An ordinary man is mistaken for the Messiah in this classic satire.",
    poster: "assets/posters/222.jpg",
    trailer: "https://www.youtube.com/results?search_query=Life+of+Brian+Official+Trailer"
},
{
    rank: 223,
    title: "Ben-Hur",
    year: 1959,
    runtime: 212,
    rating: 8.1,
    genres: ["Adventure", "Drama"],
    overview: "A Jewish prince seeks revenge after betrayal while witnessing the rise of Christ.",
    poster: "assets/posters/223.jpg",
    trailer: "https://www.youtube.com/results?search_query=Ben-Hur+1959+Official+Trailer"
},
{
    rank: 224,
    title: "Amores Perros",
    year: 2000,
    runtime: 154,
    rating: 8.1,
    genres: ["Drama", "Thriller"],
    overview: "Three interconnected stories unfold after a devastating car accident in Mexico City.",
    poster: "assets/posters/224.jpg",
    trailer: "https://www.youtube.com/results?search_query=Amores+Perros+Official+Trailer"
},
{
    rank: 225,
    title: "The Princess Bride",
    year: 1987,
    runtime: 98,
    rating: 8.0,
    genres: ["Adventure", "Comedy", "Family"],
    overview: "A fairy tale adventure filled with true love, pirates, giants and unforgettable heroes.",
    poster: "assets/posters/225.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Princess+Bride+Official+Trailer"
},
{
    rank: 226,
    title: "The Battle of Algiers",
    year: 1966,
    runtime: 121,
    rating: 8.1,
    genres: ["Drama", "History", "War"],
    overview: "A gripping portrayal of the Algerian struggle for independence against French colonial rule.",
    poster: "assets/posters/226.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Battle+of+Algiers+Official+Trailer"
},
{
    rank: 227,
    title: "The Terminator",
    year: 1984,
    runtime: 107,
    rating: 8.1,
    genres: ["Action", "Sci-Fi"],
    overview: "A cyborg assassin travels back in time to eliminate the mother of humanity's future leader.",
    poster: "assets/posters/227.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Terminator+Official+Trailer"
},
{
    rank: 228,
    title: "The Invisible Guest (Contratiempo)",
    year: 2016,
    runtime: 106,
    rating: 8.1,
    genres: ["Crime", "Mystery", "Thriller"],
    overview: "A successful businessman accused of murder hires a brilliant defense attorney.",
    poster: "assets/posters/228.jpg",
    trailer: "https://www.youtube.com/results?search_query=Contratiempo+Official+Trailer"
},
{
    rank: 229,
    title: "The Grapes of Wrath",
    year: 1940,
    runtime: 129,
    rating: 8.1,
    genres: ["Drama"],
    overview: "A struggling family heads west in search of hope during the Great Depression.",
    poster: "assets/posters/229.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Grapes+of+Wrath+Official+Trailer"
},
{
    rank: 230,
    title: "The Best Offer",
    year: 2013,
    runtime: 131,
    rating: 7.8,
    genres: ["Crime", "Drama", "Mystery"],
    overview: "A lonely art auctioneer becomes obsessed with a mysterious young woman.",
    poster: "assets/posters/230.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Best+Offer+Official+Trailer"
},
{
    rank: 231,
    title: "The Nights of Cabiria",
    year: 1957,
    runtime: 110,
    rating: 8.1,
    genres: ["Drama"],
    overview: "A resilient woman continues searching for love despite constant heartbreak.",
    poster: "assets/posters/231.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Nights+of+Cabiria+Official+Trailer"
},
{
    rank: 232,
    title: "The Return",
    year: 2003,
    runtime: 110,
    rating: 8.0,
    genres: ["Drama"],
    overview: "Two brothers embark on a mysterious journey with their estranged father.",
    poster: "assets/posters/232.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Return+2003+Official+Trailer"
},
{
    rank: 233,
    title: "Fanny and Alexander",
    year: 1982,
    runtime: 188,
    rating: 8.1,
    genres: ["Drama"],
    overview: "Two siblings navigate family tragedy and imagination in early 20th-century Sweden.",
    poster: "assets/posters/233.jpg",
    trailer: "https://www.youtube.com/results?search_query=Fanny+and+Alexander+Official+Trailer"
},
{
    rank: 234,
    title: "Children of Heaven",
    year: 1997,
    runtime: 89,
    rating: 8.2,
    genres: ["Drama", "Family"],
    overview: "A brother and sister secretly share one pair of shoes while hiding the truth from their parents.",
    poster: "assets/posters/234.jpg",
    trailer: "https://www.youtube.com/results?search_query=Children+of+Heaven+Official+Trailer"
},
{
    rank: 235,
    title: "Jai Bhim",
    year: 2021,
    runtime: 164,
    rating: 8.7,
    genres: ["Crime", "Drama"],
    overview: "A determined lawyer fights for justice on behalf of an oppressed tribal family.",
    poster: "assets/posters/235.jpg",
    trailer: "https://www.youtube.com/results?search_query=Jai+Bhim+Official+Trailer"
},
{
    rank: 236,
    title: "Andhadhun",
    year: 2018,
    runtime: 139,
    rating: 8.2,
    genres: ["Crime", "Mystery", "Thriller"],
    overview: "A blind pianist becomes entangled in a web of murder, deception and dark comedy.",
    poster: "assets/posters/236.jpg",
    trailer: "https://www.youtube.com/results?search_query=Andhadhun+Official+Trailer"
},
{
    rank: 237,
    title: "Drishyam",
    year: 2013,
    runtime: 160,
    rating: 8.2,
    genres: ["Crime", "Drama", "Thriller"],
    overview: "A cable operator uses intelligence and determination to protect his family.",
    poster: "assets/posters/237.jpg",
    trailer: "https://www.youtube.com/results?search_query=Drishyam+2013+Official+Trailer"
},
{
    rank: 238,
    title: "PK",
    year: 2014,
    runtime: 153,
    rating: 8.1,
    genres: ["Comedy", "Drama", "Sci-Fi"],
    overview: "An alien questions human beliefs and traditions after landing on Earth.",
    poster: "assets/posters/238.jpg",
    trailer: "https://www.youtube.com/results?search_query=PK+Official+Trailer"
},
{
    rank: 239,
    title: "The Bandit (Eşkıya)",
    year: 1996,
    runtime: 128,
    rating: 8.2,
    genres: ["Crime", "Drama"],
    overview: "A legendary outlaw returns to modern Istanbul after decades in prison.",
    poster: "assets/posters/239.jpg",
    trailer: "https://www.youtube.com/results?search_query=Eskiya+Official+Trailer"
},
{
    rank: 240,
    title: "Swades",
    year: 2004,
    runtime: 189,
    rating: 8.2,
    genres: ["Drama"],
    overview: "A NASA scientist returns to India and rediscovers his roots while transforming a village.",
    poster: "assets/posters/240.jpg",
    trailer: "https://www.youtube.com/results?search_query=Swades+Official+Trailer"
},
{
    rank: 241,
    title: "A Separation",
    year: 2011,
    runtime: 123,
    rating: 8.3,
    genres: ["Drama"],
    overview: "A family's separation leads to moral dilemmas and life-changing consequences.",
    poster: "assets/posters/241.jpg",
    trailer: "https://www.youtube.com/results?search_query=A+Separation+Official+Trailer"
},
{
    rank: 242,
    title: "Incendies",
    year: 2010,
    runtime: 131,
    rating: 8.3,
    genres: ["Drama", "Mystery", "War"],
    overview: "Twins uncover shocking secrets while fulfilling their mother's final wishes.",
    poster: "assets/posters/242.jpg",
    trailer: "https://www.youtube.com/results?search_query=Incendies+Official+Trailer"
},
{
    rank: 243,
    title: "My Father and My Son (Babam ve Oğlum)",
    year: 2005,
    runtime: 112,
    rating: 8.3,
    genres: ["Drama", "Family"],
    overview: "A journalist returns home with his young son after a devastating personal tragedy.",
    poster: "assets/posters/243.jpg",
    trailer: "https://www.youtube.com/results?search_query=Babam+ve+Ogulum+Official+Trailer"
},
{
    rank: 244,
    title: "The Father",
    year: 2020,
    runtime: 97,
    rating: 8.2,
    genres: ["Drama"],
    overview: "An aging man struggles to understand his changing reality while living with dementia.",
    poster: "assets/posters/244.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Father+Official+Trailer"
},
{
    rank: 245,
    title: "Green Book",
    year: 2018,
    runtime: 130,
    rating: 8.2,
    genres: ["Biography", "Comedy", "Drama"],
    overview: "A driver and a gifted pianist form an unexpected friendship during a concert tour.",
    poster: "assets/posters/245.jpg",
    trailer: "https://www.youtube.com/results?search_query=Green+Book+Official+Trailer"
},
{
    rank: 246,
    title: "The Secret in Their Eyes (El secreto de sus ojos)",
    year: 2009,
    runtime: 129,
    rating: 8.2,
    genres: ["Drama", "Mystery", "Romance"],
    overview: "A retired investigator reopens an unforgettable murder case.",
    poster: "assets/posters/246.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Secret+in+Their+Eyes+Official+Trailer"
},
{
    rank: 247,
    title: "The Hunt (Jagten)",
    year: 2012,
    runtime: 115,
    rating: 8.3,
    genres: ["Drama"],
    overview: "A respected teacher's life is shattered after a false accusation spreads through his community.",
    poster: "assets/posters/247.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Hunt+Jagten+Official+Trailer"
},
{
    rank: 248,
    title: "The Color of Paradise",
    year: 1999,
    runtime: 90,
    rating: 8.1,
    genres: ["Drama", "Family"],
    overview: "A blind boy's love for nature contrasts with his father's struggle to accept him.",
    poster: "assets/posters/248.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Color+of+Paradise+Official+Trailer"
},
{
    rank: 249,
    title: "The Message",
    year: 1976,
    runtime: 177,
    rating: 8.2,
    genres: ["Biography", "Drama", "History"],
    overview: "The story of the rise of Islam as seen through those around the Prophet Muhammad.",
    poster: "assets/posters/249.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Message+1976+Official+Trailer"
},
{
    rank: 250,
    title: "The Help",
    year: 2011,
    runtime: 146,
    rating: 8.1,
    genres: ["Drama"],
    overview: "An aspiring writer chronicles the experiences of African-American maids in 1960s Mississippi.",
    poster: "assets/posters/250.jpg",
    trailer: "https://www.youtube.com/results?search_query=The+Help+Official+Trailer"
}

];